const Tags = Object.freeze({
    SCI_FI: 'Sci-fi',
    GENDER_SWAP: 'Gender swap',
    SYSTEM: 'System',
    SOLDIER: 'Soldier',
    POLICE: 'Police',
    APOCALYPSE: 'Apocalypse',
    COUNTER_ATTACK: 'Counter attack',
    HOTBLOOD: 'Hotblood',
    EASTERN_FANTASY: 'Eastern Fantasy',
    WESTERN_FANTASY: 'Western Fantasy',
    XIANXIA: 'Xianxia',
    DETECTIVE: 'Detective',
    SPORT: 'Sport',
    MYSTERY: 'Mystery',
    CEO: 'CEO',
    EMPEROR_EMPRESS: 'Emperor/Empress',
    KING_QUEEN: 'King/Queen',
    DOCTOR: 'Doctor',
    IDOL: 'Idol',
    KILLER: 'Killer',
    KNIGHT: 'Knight',
    SUPERHERO: 'Superhero',
    SUPERMODEL: 'Supermodel',
    WITCH: 'Witch',
    GANGSTER: 'Gangster',
    SHOWBIZ: 'Showbiz',
    SUPERPOWER: 'Superpower',
    SUPERNATURAL: 'Supernatural',
    CROSSDRESSING: 'Crossdressing',
    MAGIC: 'Magic',
    HELL: 'Hell',
    MARTIAL_ART: 'Martial art',
    VAMPIRE: 'Vampire',
    SUBSTITUTE: 'Substitute',
    CATS: 'Cats',
    GHOST: 'Ghost',
    DEITIES: 'Deities',
    DRAGON: 'Dragon',
    ALIEN: 'Alien',
    GENIUS: 'Genius',
    ZOMBIE: 'Zombie',
    ANIMAL: 'Animal',
    ROBOT: 'Robot',
    BABY: 'Baby',
    ARRANGED_MARRIAGE: 'Arranged Marriage',
    COHABITATING: 'Cohabitating',
    LOVE_AT_FIRST_SIGHT: 'Love at first sight',
    REUNION: 'Reunion',
    HAREM: 'Harem',
    REVENGE: 'Revenge',
    REINCARNATION: 'Reincarnation',
    CHUANYUE: 'Chuanyue',
    BODY_SWAP: 'Body swap',
    TRANSFORMATION: 'Transformation',
    HIDE_IDENTITY: 'Hide Identity',
    CRIME: 'Crime',
    MEMORY_LOSS: 'Memory loss',
    SURVIVAL_GAME: 'Survival Game',
    SECRET_LOVE: 'Secret love',
    LOVE_TRIANGLE: 'Love Triangle',
    FORBIDDEN_LOVE: 'Forbidden Love',
    TRAGIC: 'Tragic',
    HEARTWARMING: 'Heartwarming',
    INSPIRATIONAL: 'Inspirational',
    SATISFYING: 'Satisfying',
    DARK: 'Dark',
    NOBILITY: 'Nobility',
    CAMPUS: 'Campus',
    OFFICE: 'Office',
    IMPERIAL_COURT: 'Imperial court',
    CONTEMPORARY: 'Contemporary',
    LEVEL_UP: 'Level up',
    HISTORICAL: 'Historical',
    FICTIONAL_UNIVERSE: 'Fictional universe',
    EXTRA_LONG: 'Extra-long',
    SHORT: 'Short',
    SLICE_OF_LIFE: 'Slice of Life',
    KINSHIP: 'Kinship',
    FRIENDSHIP: 'Friendship',
    EX_LOVER: 'Ex lover',
    TEACHER: 'Teacher',
    CHILDHOOD_SWEETHEART: 'Childhood sweetheart',
    ACTOR: 'Actor',
    AGENT: 'Agent',
    ABO: 'ABO',
    ANCHOR: 'Anchor',
    SWEET: 'Sweet',
    FUTURE: 'Future',
    ARTIST: 'Artist',
    WEREWOLF: 'Werewolf',
    BETRAYAL: 'Betrayal',
    REVERSE_HAREM: 'Reverse harem',
    CONTRACT_MARRIAGE: 'Contract marriage',
    VIDEO_GAME: 'Video game',
    ANTHOLOGY: 'Anthology',
    OVERPOWERED: 'Overpowered',
    PREGNANCY: 'Pregnancy',
    URBAN: 'Urban',
    FORCED_LOVE: 'Forced love',
    ISEKAI: 'Isekai',
    FAMILY_FEUD: 'Family feud',
    ENEMIES_TO_LOVERS: 'Enemies to lovers',
    MONSTER: 'Monster',
    ONE_NIGHT_STAND: 'One-night stand',
    METAPHYSICS: 'Metaphysics',
    AGE_GAP: 'Age gap',
    DEMON: 'Demon',
    PRINCE_PRINCESS: 'Prince/Princess',
    FATED: 'Fated',
    BOSSY: 'Bossy',
    LEADING_LADIES: 'Leading ladies',
    BAD_BOY: 'Bad Boy',
    BAD_GIRL: 'Bad girl',
    ACTION: 'Action'
});

export default Tags;
