# Generated by Django 5.0.4 on 2024-05-04 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Something',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a', models.BooleanField()),
                ('b', models.BooleanField()),
            ],
            options={
                'db_table': 'somethgin',
                'managed': False,
            },
        ),
    ]
