# Generated by Django 5.0.4 on 2024-05-04 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_something'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Something',
        ),
    ]
